[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_USE_YARN = "false"
  NPM_VERSION = "10.9.7"
